"""UTBMS (Uniform Task-Based Management System) code reference — LEDES Code Set II
(1999B). Static reference data, NOT a MyCase API endpoint: firms using LEDES billing
tag Time Entries with these via utbms_activity_code / utbms_task_code. A task code
may stand alone; an activity code requires an accompanying task code.

Source: MyCase API docs "UTBMS Codes" guide (Session 25). Kept as a lookup TOOL
rather than embedded in the system prompt so the ~220-code table doesn't cost tokens
on every turn — only fetched when actually needed.
"""
from __future__ import annotations

ACTIVITY_CODES: dict[str, str] = {
    "A101": "Plan and prepare for",
    "A102": "Research",
    "A103": "Draft/Revise",
    "A104": "Review/Analyze",
    "A105": "Communicate (within legal team)",
    "A106": "Communicate (with client)",
    "A107": "Communicate (opponents/other outside counsel)",
    "A108": "Communicate (other external)",
    "A109": "Appear For/Attend",
    "A110": "Manage Data/Files/Documentation",
    "A111": "Other",
    "A112": "Billable Travel Time",
    "A113": "Communicate (witnesses)",
    "A114": "Communicate (experts)",
    "A115": "Medical Record and Medical Bill Management",
    "A116": "Training",
    "A117": "Special Handling Copying/Scanning/Imaging (Internal)",
    "A118": "Collection-Forensic",
    "A119": "Culling & Filtering",
    "A120": "Processing",
    "A121": "Review and Analysis",
    "A122": "Quality Assurance and Control",
    "A123": "Search Creation and Execution",
    "A124": "Privilege Review Culling and Log Creation",
    "A125": "Document Production Creation and Preparation",
    "A126": "Evidence/Exhibit Creation and Preparation",
    "A127": "Project Management",
    "A128": "Collection Closing Activities",
}

TASK_CODES: dict[str, str] = {
    "L100": "Case Assessment, Development and Administration",
    "L110": "Fact Investigation/Development",
    "L120": "Analysis/Strategy",
    "L130": "Experts/Consultants",
    "L140": "Document/File Management",
    "L150": "Budgeting",
    "L160": "Settlement/Non-Binding ADR",
    "L190": "Other Case Assessment, Development and Administration",
    "L200": "Pre-Trial Pleadings and Motions",
    "L210": "Pleadings",
    "L220": "Preliminary Injunctions/Provisional Remedies",
    "L230": "Court Mandated Conferences",
    "L240": "Dispositive Motions",
    "L250": "Other Written Motions and Submissions",
    "L260": "Class Action Certification and Notice",
    "L300": "Discovery",
    "L310": "Written Discovery",
    "L320": "Document Production",
    "L330": "Depositions",
    "L340": "Expert Discovery",
    "L350": "Discovery Motions",
    "L390": "Other Discovery",
    "L400": "Trial Preparation and Trial",
    "L410": "Fact Witnesses",
    "L420": "Expert Witnesses",
    "L430": "Written Motions and Submissions",
    "L440": "Other Trial Preparation and Support",
    "L450": "Trial and Hearing Attendance",
    "L460": "Post-Trial Motions and Submissions",
    "L470": "Enforcement",
    "L500": "Appeal",
    "L510": "Appellate Motions and Submissions",
    "L520": "Appellate Briefs",
    "L530": "Oral Argument",
    "L600": "Identification",
    "L601": "Discovery planning",
    "L602": "Interviews",
    "L609": "Quality assurance and control",
    "L610": "Preservation",
    "L611": "Preservation order",
    "L612": "Legal hold",
    "L619": "Quality assurance and control",
    "L620": "Collection",
    "L621": "Collection/Recovery",
    "L622": "Media costs",
    "L623": "Media/ESI Transfer, Receipt, Inventory",
    "L629": "Quality assurance and control",
    "L630": "Processing",
    "L631": "ESI stage, preparation and process",
    "L632": "Scanning - Hard Copy",
    "L633": "Foreign language translation",
    "L634": "Exception handling",
    "L639": "Quality assurance and control",
    "L650": "Review",
    "L651": "Hosting costs",
    "L652": "Objective and Subjective coding",
    "L653": "First pass document review",
    "L654": "Second pass document review",
    "L655": "Privilege review",
    "L656": "Redaction",
    "L659": "Quality assurance and control",
    "L660": "Analysis",
    "L670": "Production",
    "L671": "Conversion of ESI to production format",
    "L679": "Quality assurance and control",
    "L680": "Presentation",
    "L690": "Project Management",
    "L693": "Review Planning & Training",
    "C100": "Fact Gathering",
    "C200": "Researching Law",
    "C300": "Analysis and Advice",
    "C400": "Third Party Communication",
    "P100": "Project Administration",
    "P200": "Fact Gathering/Due Diligence",
    "P210": "Corporate Review",
    "P220": "Tax",
    "P230": "Environmental",
    "P240": "Real and Personal Property",
    "P250": "Employee/Labor",
    "P260": "Intellectual Property",
    "P270": "Regulatory Reviews",
    "P280": "Other",
    "P300": "Structure/Strategy/Analysis",
    "P400": "Initial Document Preparation/Filing",
    "P500": "Negotiation/Revision/Responses",
    "P600": "Completion/Closing",
    "P700": "Post-Completion/Post-Closing",
    "P800": "Maintenance and Renewal",
    "B100": "Administration",
    "B110": "Case Administration",
    "B120": "Asset Analysis and Recovery",
    "B130": "Asset Disposition",
    "B140": "Relief from Stay/Adequate Protection Proceedings",
    "B150": "Meetings of and Communications with Creditors",
    "B160": "Fee/Employment Applications",
    "B170": "Fee/Employment Objections",
    "B180": "Avoidance Action Analysis",
    "B185": "Assumption/Rejection of Leases and Contracts",
    "B190": "Other Contested Matters (excluding assumption/rejection motions)",
    "B195": "Non-Working Travel",
    "B200": "Operations",
    "B210": "Business Operations",
    "B220": "Employee Benefits/Pensions",
    "B230": "Financing/Cash Collections",
    "B240": "Tax Issues",
    "B250": "Real Estate",
    "B260": "Board of Directors Matters",
    "B300": "Claims and Plan",
    "B310": "Claims Administration and Objections",
    "B320": "Plan and Disclosure Statement (including Business Plan)",
    "B400": "Bankruptcy-Related Advice",
    "B410": "General Bankruptcy Advice/Opinions",
    "B420": "Restructurings",
    "PA100": "Assessment, Development, and Administration",
    "PA110": "Fact Investigation and Development",
    "PA120": "Analysis/Strategy",
    "PA130": "Document/File Management",
    "PA140": "Budgeting",
    "PA199": "Other Assessment, Development, or Administration",
    "PA200": "Patent Investigation and Analysis",
    "PA210": "State-of-the-Art Investigation",
    "PA220": "Patentability Investigation",
    "PA230": "Clearance Investigation",
    "PA240": "Validity Investigation",
    "PA250": "Publication Watches",
    "PA260": "Infringement Investigation",
    "PA270": "Status Investigation",
    "PA299": "Other Patent Investigation and Analysis",
    "PA300": "Domestic Patent Preparation",
    "PA310": "Provisional Application Preparation - Domestic",
    "PA320": "Non-Provisional Application Preparation - Domestic",
    "PA330": "Design Application Preparation - Domestic",
    "PA340": "Plant Patent Preparation - Domestic",
    "PA350": "Continuing Application Preparation - Domestic",
    "PA360": "Validation Patent Application Preparation - Domestic",
    "PA399": "Other Patent Application Preparation - Domestic",
    "PA400": "Domestic Patent Prosecution",
    "PA410": "Information Disclosure Statement - Domestic",
    "PA420": "Preliminary Amendment - Domestic",
    "PA430": "Official Communication - Domestic",
    "PA440": "Quasi-Judicial Administrative Proceedings - Domestic",
    "PA450": "Post-Issuance Remedial Action - Domestic",
    "PA499": "Other Patent Prosecution - Domestic",
    "PA500": "International Patent Preparation",
    "PA510": "Provisional Application Preparation - International",
    "PA520": "Non-Provisional Application Preparation - International",
    "PA530": "Design Application Preparation - International",
    "PA540": "Plant Patent Preparation - International",
    "PA550": "Continuing Application Preparation - International",
    "PA560": "Validation Patent Application Preparation - International",
    "PA599": "Other Patent Application Preparation - International",
    "PA600": "International Patent Prosecution",
    "PA610": "Information Disclosure Statement - International",
    "PA620": "Preliminary Amendment - International",
    "PA630": "Official Communication - International",
    "PA640": "Quasi-Judicial Administrative Proceedings - International",
    "PA650": "Post-Issuance Remedial Action - International",
    "PA699": "Other Patent Prosecution - International",
    "PA700": "Other Patent-Related Tasks",
    "PA710": "Opinion Preparation",
    "PA720": "Portfolio Analysis and Management",
    "PA730": "Assignments and Security Interests",
    "PA740": "Licensing",
    "TR100": "Assessment, Development, and Administration",
    "TR110": "Fact Investigation and Development",
    "TR120": "Analysis/Strategy",
    "TR130": "Document/File Management",
    "TR140": "Budgeting",
    "TR199": "Other Assessment, Development, or Administration",
    "TR200": "Trademark Investigation and Analysis",
    "TR220": "Registerability Investigation",
    "TR230": "Clearance Investigation",
    "TR240": "Opposition Investigation",
    "TR250": "Publication Watches",
    "TR260": "Enforcement Investigation",
    "TR270": "Status Investigation",
    "TR299": "Other Trademark Investigation and Analysis",
    "TR300": "Domestic Trademark Application Preparation",
    "TR310": "Application Preparation and Filing - Domestic",
    "TR399": "Other Domestic Trademark Application Preparation and Filing",
    "TR400": "Domestic Trademark Prosecution and Renewal",
    "TR410": "Aff., Pet., Ext., Decl. and Other Filings - Domestic",
    "TR420": "Preliminary Amendment - Domestic",
    "TR430": "Official Communication - Domestic",
    "TR440": "Quasi-Judicial Administrative Proceedings - Domestic",
    "TR499": "Other Trademark Prosecution - Domestic",
    "TR500": "International Trademark Application Preparation and Renewals",
    "TR510": "Application Preparation and Filing - International",
    "TR599": "Other International Trademark Application Prep. and Filing",
    "TR600": "International Trademark Prosecution and Renewal",
    "TR610": "Aff., Pet., Ext., Decl. and Other Filings - International",
    "TR620": "Preliminary Amendment - International",
    "TR630": "Official Communication - International",
    "TR640": "Quasi-Judicial Administrative Proceedings - International",
    "TR699": "Other Trademark Prosecution - International",
    "TR700": "Other Trademark Related Tasks",
    "TR710": "Opinion Preparation",
    "TR720": "Portfolio Analysis and Management",
    "TR730": "Assignments and Security Interests",
    "TR740": "Licensing",
    "TR750": "Domain Names - gTLDs",
    "TR760": "Domain Names - ccTLDs",
    "TR770": "Quasi-Judicial Administrative Proceedings - Domain Names",
    "TR799": "Other Trademark Prosecution",
    "JA10": "Funding",
    "JB10": "Budgeting - own side's costs",
    "JB20": "Budgeting - Precedent H",
    "JB30": "Budgeting - between the parties",
    "JC10": "Factual investigation",
    "JC20": "Legal investigation",
    "JC30": "Pre-action protocol (or similar) work",
    "JD10": "Mediation",
    "JD20": "Other Settlement Matters",
    "JE10": "Issue and Serve Proceedings and Preparation of Statement(s) of Case",
    "JE20": "Review of Other Party(s)' Statements of Case",
    "JE30": "Requests for Further Information",
    "JE40": "Amendment of Statements of Case",
    "JF10": "Preparation of the disclosure report and the disclosure proposal",
    "JF20": "Obtaining and reviewing documents",
    "JF30": "Preparing and serving disclosure lists",
    "JF40": "Inspection and review of the other side's disclosure for work undertaken after exchange of disclosure lists",
    "JG10": "Taking, preparing and finalising witness statement(s)",
    "JG20": "Reviewing Other Party(s)' witness statement(s)",
    "JH10": "Own expert evidence",
    "JH20": "Other Party(s)' expert evidence",
    "JH30": "Joint expert evidence",
    "JI10": "Case Management Conference",
    "JI20": "Pre Trial Review",
    "JI30": "Costs Management Conference",
    "JJ10": "Applications relating to originating process or Statement of Case or for default or summary judgment",
    "JJ20": "Applications for an injunction or committal",
    "JJ30": "Applications for disclosure or Further Information",
    "JJ40": "Applications concerning evidence",
    "JJ50": "Applications relating to Costs alone",
    "JJ60": "Permission applications",
    "JJ70": "Other applications",
    "JK10": "Preparation of trial bundles",
    "JK20": "General work regarding preparation for trial",
    "JL10": "Advocacy",
    "JL20": "Support of advocates",
    "JL30": "Judgment and post-trial activity",
    "JM10": "Preparing costs claim",
    "JM20": "Points of dispute, Replies and Negotiations",
    "JM30": "Hearings",
    "JM40": "Post Assessment Work (excluding Hearings)",
}


def lookup_utbms_code(code: str) -> dict[str, str] | None:
    """Look up a UTBMS activity or task code (case-insensitive). Returns
    {"code", "type": "activity"|"task", "description"} or None if not found."""
    c = (code or "").strip().upper()
    if c in ACTIVITY_CODES:
        return {"code": c, "type": "activity", "description": ACTIVITY_CODES[c]}
    if c in TASK_CODES:
        return {"code": c, "type": "task", "description": TASK_CODES[c]}
    return None
